name: Continuous Integration

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
  pull_request:
  workflow_dispatch:

env:
  FORCE_COLOR: "1"
  TOX_TESTENV_PASSENV: FORCE_COLOR

jobs:
  tests:
    name: Test implementation
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.9"
          - "3.8"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - run: tox

  package:
    name: Test package build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Build and test dist
        run: |
          python -m pip install build twine check-wheel-contents
          python -m build --sdist --wheel .
          ls -l dist
          check-wheel-contents dist/*.whl
          python -m twine check dist/*
